// 메인 퀘스트: 순서대로 진행. type
//  talk  : npc에게 말 걸기 (lines를 듣고 나면 완료)
//  wave  : 그 지역의 북·방울·범종을 울려 밤 싸움에서 이기기
//  kill  : 몬스터 처치 (need: {종류: 수})
//  collect: 몬스터가 떨어뜨리는 퀘스트 물건 모으기 (from 종류, chance 확률)
//  light : 그 지역(region)의 꺼진 석등 밝히기 (E 키)
// gate: 이 단계가 시작될 때 열리는 문, reward: 완료 보상 (exp, item: 'cls:티어' 또는 아이템 id)
export const QUESTS = [
  { title: '수문장을 찾아서', type: 'talk', npc: 'guard', desc: '왼쪽 북 옆의 <b>수문장</b>에게 말을 걸자',
    lines: (g) => [
      `어이, 거기 젊은 ${g.player.cfg.title}! 마침 잘 왔소.`,
      '해만 지면 이 궁궐 마당에 도깨비 놈들이 떼로 몰려와 난장판을 친다오.',
      '저기 저 큰 북이 보이시오? 북을 둥— 하고 울리면 숨어 있던 놈들이 죄다 튀어나올 게요.',
      '놈들을 모조리 혼쭐내 주시오! 마지막엔 도깨비 대왕이 나온다는 소문이 있으니 조심하고.',
      '(북 앞에서 E 키, 혹은 검으로 북을 베어 울리세요)',
    ] },
  { title: '도깨비 야행', type: 'wave', region: 'palace', desc: '<b>큰 북</b>을 울려 도깨비들을 물리치자', reward: { exp: 60 } },
  { title: '북채 도둑', type: 'chase', region: 'palace', mob: 'blue', thiefName: '북채 도둑', item: '북채', hpMul: 3, added: 4, desc: '<b>북채</b>를 훔쳐 달아난 <b>꼬마 도깨비</b>를 붙잡자 (구석에 몰거나 기술로 길을 끊자)', reward: { exp: 60 },
    startLines: ['수문장: 이런! 달아나던 꼬마 도깨비 놈이 내 북채를 채 갔소!', '수문장: 가까이 가면 줄행랑을 치니, 담 구석으로 몰거나 기술로 길을 끊으시오!'] },
  { title: '남문이 열리다', type: 'talk', npc: 'guard', desc: '<b>수문장</b>에게 돌아가 알리자',
    lines: () => [
      '허허, 대왕까지 쫓아내다니! 이 궁의 은인이시구려.',
      '실은 부탁이 하나 더 있소. 남문 밖 대숲에서 요즘 여우들이 사람을 홀린다 하오.',
      '남문을 열어 드리리다. 죽림 어귀에 약초꾼 분이가 있으니 사정을 들어 보시오.',
      '이건 고마움의 표시요. 색동 저고리인데, 입으면 몸이 한결 가벼울 게요.',
    ], gateAfter: 'south', reward: { exp: 40, item: 'ot5' } },
  { title: '죽림 어귀', type: 'talk', npc: 'herb', desc: '남문 밖 <b>죽림 어귀</b>의 약초꾼 <b>분이</b>를 찾아가자',
    lines: () => [
      '어머나, 궁에서 오셨어요? 수문장 어르신이 보내셨구나!',
      '요즘 숲에 여우들이 들끓어서 약초를 캘 수가 없어요.',
      '숲을 어슬렁거리는 여우들을 좀 쫓아 주실래요? 가까이 가면 달려드니 조심하세요.',
    ] },
  { title: '여우 사냥', type: 'kill', need: { fox: 10 }, desc: '죽림을 돌아다니는 <b>여우</b>를 사냥하자', reward: { exp: 90 } },
  { title: '여우의 홀림', type: 'search', region: 'bamboo', n: 4, item: '여우 부적', added: 4, desc: '대숲 곳곳에 숨은 <b>여우 부적</b>을 찾아 떼어 내자 (가까이 가면 방울 소리가 나요)', reward: { exp: 110 },
    startLines: ['분이: 여우들이 대숲 여기저기에 부적을 붙여 사람 길을 홀리고 있대요.', '분이: 가까이 가면 딸랑딸랑 방울 소리가 나요. 반짝이는 부적 넷만 찾아 떼어 주세요!'] },
  { title: '여우불 구슬', type: 'collect', item: '여우구슬', from: ['foxfire'], chance: 0.5, n: 6, desc: '<b>여우불</b>을 쓰러뜨려 <b>여우구슬</b>을 모으자', reward: { exp: 90, item: 'cls:2' },
    startLines: ['분이: 여우불이 품은 구슬이 있으면 서낭당의 부정을 씻을 수 있대요.', '분이: 숲속 주황 불덩이들을 쓰러뜨려 구슬을 여섯 개만 모아 주세요!'] },
  { title: '서낭당의 방울', type: 'wave', region: 'bamboo', desc: '숲 한가운데 <b>서낭당 방울</b>을 울려 <b>구미호</b>를 불러내자', reward: { exp: 180 },
    startLines: ['분이: 구슬을 서낭당에 바쳤더니 방울이 울릴 준비가 됐어요.', '분이: 방울을 흔들면 천년 묵은 구미호가 나타날 거예요… 부디 조심하세요!'] },
  { title: '대숲 너머', type: 'talk', npc: 'hermit', desc: '죽림 남쪽 끝, 폐사찰 일주문 앞의 <b>떠돌이 도사</b>를 찾아가자',
    lines: () => [
      '허허, 구미호를 물리친 이가 자네로군. 기다리고 있었네.',
      '이 일주문 너머는 버려진 옛 절터일세. 저승사자가 망자들을 풀어놓고 있지.',
      '금줄을 걷어 주겠네. 들어가거든 떠도는 망자들부터 잠재우게.',
    ], gateAfter: 'temple', reward: { exp: 60 } },
  { title: '떠도는 망자', type: 'kill', need: { jiangshi: 8, ghost: 5 }, desc: '눈밭의 <b>강시</b>와 <b>원귀</b>를 잠재우자', reward: { exp: 160 } },
  { title: '꺼진 석등', type: 'light', n: 4, desc: '폐사찰의 꺼진 <b>석등</b>에 불을 밝히자 (석등 앞에서 E)', reward: { exp: 120, item: 'ot8' },
    startLines: ['청허: 망자들이 잠잠해졌군. 이제 꺼진 석등에 불을 밝혀 길을 비추게.', '청허: 불이 넷 켜지면 저승의 문이 드러날 걸세.'] },
  { title: '망자의 비석', type: 'order', region: 'temple', n: 4, prop: 'stele', added: 4, wrongLine: '순서가 틀렸다! 망자가 깨어난다', desc: '새겨진 <b>점이 적은 비석부터</b> 차례로 두드리자 (비석 앞에서 E)', reward: { exp: 150 },
    startLines: ['청허: 종각 앞에 비석 넷이 서 있네. 저승의 순서를 지켜야 범종이 울리지.', '청허: 새겨진 점이 적은 비석부터 많은 비석 순으로 두드리게. 틀리면 망자가 깨어나니 조심하고.'] },
  { title: '저승의 문', type: 'wave', region: 'temple', desc: '종각의 <b>범종</b>을 울려 <b>저승사자</b>와 맞서자', reward: { exp: 300 },
    startLines: ['청허: 석등이 모두 밝았네. 종각의 범종을 울리면 저승사자가 명부를 들고 올 걸세.'] },
  { title: '뒷문 너머', type: 'talk', npc: 'hermit', desc: '폐사찰 입구의 <b>떠돌이 도사 청허</b>와 이야기하자',
    lines: () => [
      '저승사자가 물러갔구먼. 헌데 명부가 흩어지며 남쪽 늪의 물안개가 짙어졌다네.',
      '절 뒤편 쪽문 너머는 물안개 늪일세. 천 년 동안 용이 되기를 기다린 이무기가 잠들어 있지.',
      '쪽문의 부적을 떼어 주겠네. 늪 어귀의 사공 영감이 길을 알 걸세.',
      '(물에 들어가면 걸음이 느려집니다. 나무 다리를 따라가세요)',
    ], gateAfter: 'swamp', reward: { exp: 150 } },
  { title: '늪의 사공', type: 'talk', npc: 'ferry', desc: '폐사찰 뒷문 너머 <b>물안개 늪</b>의 <b>사공 영감</b>을 찾아가자',
    lines: () => [
      '허, 이런 데까지 사람이 다 오는구먼. 난 이 늪에서 나룻배를 젓는 늙은이요.',
      '요새 물귀신들이 사람 발목을 잡아끌고, 두꺼비 요괴가 독을 뱉어 배를 띄울 수가 없소.',
      '물귀신은 물속에선 빨라지니 뭍이나 다리 위에서 상대하시오.',
    ] },
  { title: '물귀신 소동', type: 'kill', region: 'swamp', need: { waterghost: 9, toad: 5 }, desc: '늪의 <b>물귀신</b>과 <b>두꺼비 요괴</b>를 물리치자', reward: { exp: 260, item: 'cls:3' } },
  { title: '연꽃 등불', type: 'light', region: 'swamp', n: 3, desc: '늪 작은 섬들의 <b>석등</b>에 불을 밝히자 (석등 앞에서 E)', reward: { exp: 220 },
    startLines: ['사공: 고맙소! 물안개를 걷으려면 섬마다 있는 석등에 불을 켜야 하오.', '사공: 셋이 다 켜지면 제단의 징을 울릴 수 있을 게요.'] },
  { title: '사공의 뱃길', type: 'escort', region: 'swamp', npc: 'ferry', added: 4, ambushLine: '물귀신이 덮친다! 사공을 지키자', desc: '<b>사공 영감</b>을 용왕 제단까지 지켜 드리자 (곁에 붙어 있어야 걸어요)', reward: { exp: 280 },
    startLines: ['사공: 제단의 징은 나만 걸 수 있소. 날 제단까지 데려다주시오.', '사공: 늙은이라 혼자는 못 가오. 곁에 붙어 있어야 걸음을 떼겠소. 물귀신이 덤비면 막아 주시고!'] },
  { title: '이무기의 징', type: 'wave', region: 'swamp', desc: '용왕 제단의 <b>징</b>을 울려 <b>천년 이무기</b>와 맞서자', reward: { exp: 500 },
    startLines: ['사공: 징을 치면 이무기가 깨어날 거요. 놈은 물속으로 숨었다가 발밑에서 솟구치니, 바닥의 푸른 원을 보면 피하시오!'] },
  { title: '막힌 길', type: 'talk', npc: 'ferry', desc: '늪 어귀의 <b>사공 영감</b>에게 돌아가자',
    lines: () => [
      '이무기가 잠잠해지니 늪에 햇살이 다 드는구려! 정말 고맙소.',
      '헌데 그놈이 날뛰는 통에 남쪽 협곡 길이 바위로 막혔다오. 내가 장정들을 불러 치워 두리다.',
      '협곡엔 옛 대장간이 있소. 쇠를 먹는 괴물 불가사리가 깨어났다는 흉흉한 소문이…',
    ], gateAfter: 'canyon', reward: { exp: 200 } },
  { title: '대장장이', type: 'talk', npc: 'smith', desc: '늪 남동쪽 길 너머 <b>불가사리 협곡</b>의 <b>대장장이</b>를 찾아가자',
    lines: () => [
      '여기까지 왔으면 보통 솜씨가 아니구먼. 난 이 대장간을 지키던 쇠돌이요.',
      '불가사리가 쇠를 먹어 치우더니 가마의 불이 화염 도깨비가 되고, 장승들이 돌덩이 병사가 됐소.',
      '놈들부터 정리해 주시오. 분화구가 벌겋게 달아오르면 피하고!',
    ] },
  { title: '불씨 사냥', type: 'kill', region: 'canyon', need: { firedok: 9, stonegolem: 3 }, desc: '협곡의 <b>화염 도깨비</b>와 <b>돌장승</b>을 물리치자', reward: { exp: 380 } },
  { title: '검은 쇳조각', type: 'collect', region: 'canyon', item: '검은 쇳조각', from: ['firedok', 'stonegolem'], chance: 0.4, n: 7, desc: '쓰러뜨린 적에게서 <b>검은 쇳조각</b>을 모으자', reward: { exp: 300, item: 'cls:4' },
    startLines: ['쇠돌이: 불가사리를 불러내려면 놈이 좋아하는 검은 쇳조각이 있어야 하오.', '쇠돌이: 협곡의 놈들이 품고 있으니 일곱 개만 모아 오시오.'] },
  { title: '가마 지키기', type: 'hold', region: 'canyon', time: 40, added: 4, desc: '대장간 앞 <b>원</b> 안에서 버티며 가마의 불씨를 지키자 (원 밖이면 시간이 멈춰요)', reward: { exp: 360 },
    startLines: ['쇠돌이: 쇳조각을 녹이려면 가마 불이 꺼지면 안 되오. 그런데 화염 도깨비들이 불씨를 훔치러 몰려올 거요!', '쇠돌이: 가마 앞 원 안에서 사십 초만 버텨 주시오. 원 밖으로 나가면 불이 식어 시간이 멈추오.'] },
  { title: '불가사리의 풀무', type: 'wave', region: 'canyon', desc: '대장간의 <b>풀무</b>를 밟아 <b>불가사리</b>를 불러내자', reward: { exp: 700 },
    startLines: ['쇠돌이: 쇳조각을 가마에 넣었소. 풀무를 밟으면 냄새를 맡고 불가사리가 올 거요.', '쇠돌이: 놈이 쇳조각을 뿜으면 붉은 원을 피하시오. 다치면 몸이 달아올라 더 사나워지오!'] },
  { title: '산길 너머', type: 'talk', npc: 'smith', desc: '협곡 대장간의 <b>대장장이 쇠돌이</b>와 이야기하자',
    lines: () => [
      '불가사리를 녹여 버리다니! 이 쇠돌이, 평생 이런 솜씨는 처음 보오.',
      '헌데 놈이 쓰러지던 밤, 남쪽 산에서 범 울음이 들렸소. 단풍 든 옛 산성 쪽이오.',
      '산적 도깨비들이 산성을 차지하고, 산군 백호까지 깨어났다는구려. 산길을 막은 목책을 치워 두리다.',
      '산성 어귀에 의병장 어른이 버티고 계시니 찾아가 보시오.',
    ], gateAfter: 'fortress', reward: { exp: 300 } },
  { title: '산성의 의병장', type: 'talk', npc: 'captain', desc: '협곡 남동쪽 산길 너머 <b>단풍 산성</b>의 <b>의병장</b>을 찾아가자',
    lines: () => [
      '거기 누구냐! …사람이로군. 이 산성을 지키던 의병장 강호요.',
      '산적 도깨비 놈들이 성을 빼앗고, 까마귀 요괴들이 하늘에서 깃털 화살을 퍼붓소.',
      '까마귀는 세 발씩 부채꼴로 쏘니 옆으로 비켜서시오. 놈들부터 몰아내 주시오!',
    ] },
  { title: '산적 소탕', type: 'kill', region: 'fortress', need: { bandit: 10, crow: 6 }, desc: '산성의 <b>산적 도깨비</b>와 <b>까마귀 요괴</b>를 물리치자', reward: { exp: 520 } },
  { title: '범 발톱', type: 'collect', region: 'fortress', item: '범 발톱', from: ['tiger'], chance: 0.6, n: 5, desc: '산을 누비는 <b>범</b>을 쓰러뜨려 <b>범 발톱</b>을 모으자', reward: { exp: 480, item: 'ot12' },
    startLines: ['강호: 백호를 불러내려면 그 자식들인 범의 발톱을 봉화에 태워야 하오.', '강호: 범은 몸을 날려 덮치니 조심하고, 발톱 다섯 개만 모아 오시오.'] },
  { title: '전령 까마귀', type: 'chase', region: 'fortress', mob: 'crow', thiefName: '전령 까마귀', item: '밀서', hpMul: 4, added: 4, desc: '산적의 <b>밀서</b>를 물고 달아나는 <b>까마귀</b>를 붙잡자', reward: { exp: 500 },
    startLines: ['강호: 저 까마귀 놈이 산적의 밀서를 물고 있소! 놓치면 봉화를 올릴 때 놈들이 먼저 알고 덮칠 거요.', '강호: 쫓아가 떨어뜨리시오. 기술로 길을 끊으면 잡기 쉬울 거요.'] },
  { title: '봉수대', type: 'light', region: 'fortress', n: 3, desc: '성곽의 꺼진 <b>봉수대</b>에 불을 붙이자 (봉수대 앞에서 E)', reward: { exp: 450 },
    startLines: ['강호: 발톱을 모았으니 이제 성곽의 봉수대 셋에 불을 붙이시오.', '강호: 셋이 다 타오르면 안마당의 큰 봉화를 올릴 수 있소.'] },
  { title: '산군의 봉화', type: 'wave', region: 'fortress', desc: '안마당의 <b>봉화</b>를 올려 <b>산군 백호</b>와 맞서자', reward: { exp: 950 },
    startLines: ['강호: 봉화를 올리면 산군이 내려올 거요. 놈이 몸을 낮추면 돌진이니 옆으로 피하시오!', '강호: 다칠수록 쉬지 않고 덤비오. 각오하시오.'] },
  { title: '바닷길', type: 'talk', npc: 'captain', desc: '산성 어귀의 <b>의병장 강호</b>에게 돌아가자',
    lines: () => [
      '백호가 물러가니 산이 다 조용하구려! 이 은혜를 어찌 갚겠소.',
      '헌데 백호가 쓰러지며 남서쪽 바닷가 바위 사이로 물길이 열렸다오. 그 아래가 용궁이라는 전설이 있소.',
      '바위 사이 금줄을 걷어 두리다. 물길로 내려가면 용궁의 사신이 마중 나올 게요.',
    ], gateAfter: 'sea', reward: { exp: 350 } },
  { title: '용궁의 사신', type: 'talk', npc: 'envoy', desc: '산성 남서쪽 물길 아래 <b>용궁</b>의 <b>용녀</b>를 찾아가자',
    lines: () => [
      '뭍의 손님이시군요. 저는 용왕님을 모시는 용녀 해랑이에요.',
      '용왕님이 깨진 거울 조각을 삼키신 뒤로 성정이 사나워지셨어요. 경비대도 뭍사람만 보면 덤벼들고요.',
      '꽃게 병사는 등딱지가 단단하고, 해파리의 독 방울을 맞으면 몸이 무거워져요. 먼저 경비대를 달래 주세요.',
    ] },
  { title: '용궁 경비대', type: 'kill', region: 'sea', need: { crab: 10, jelly: 6 }, desc: '용궁의 <b>꽃게 병사</b>와 <b>해파리</b>를 물리치자', reward: { exp: 700 } },
  { title: '거북 장군', type: 'kill', region: 'sea', need: { turtle: 4 }, desc: '용궁을 지키는 <b>거북 장군</b>을 물리치자', reward: { exp: 650, item: 'ot11' },
    startLines: ['해랑: 경비대장인 거북 장군들이 길을 막고 있어요. 등딱지로 내려찍으니 붉은 원을 피하세요.', '해랑: 아주 단단하니 얼리거나 기술로 몰아치세요!'] },
  { title: '흩어진 진주', type: 'search', region: 'sea', n: 4, item: '진주', added: 4, desc: '용궁 곳곳에 흩어진 <b>진주</b>를 찾아 모으자 (가까이 가면 맑은 소리가 나요)', reward: { exp: 620 },
    startLines: ['해랑: 진주 등을 밝히려면 등에 넣을 진주가 있어야 해요. 경비대가 날뛰는 통에 다 흩어졌어요.', '해랑: 진주는 가까이 가면 맑게 울려요. 넷만 찾아 주세요!'] },
  { title: '진주 등', type: 'light', region: 'sea', n: 3, desc: '용궁의 꺼진 <b>진주 등</b>을 밝히자 (진주 등 앞에서 E)', reward: { exp: 600 },
    startLines: ['해랑: 용궁의 진주 등 셋이 꺼져 있어요. 다시 밝히면 용고를 울릴 수 있어요.'] },
  { title: '용고', type: 'wave', region: 'sea', desc: '본전 앞 <b>용고</b>를 울려 <b>동해 용왕</b>과 맞서자', reward: { exp: 1300 },
    startLines: ['해랑: 용고를 울리면 용왕님이 나오실 거예요. 물속으로 사라지면 발밑의 푸른 원을, 하늘이 번쩍이면 벼락을 피하세요!'] },
  { title: '샘물길', type: 'talk', npc: 'envoy', desc: '용궁 어귀의 <b>용녀 해랑</b>에게 돌아가자',
    lines: () => [
      '용왕님이 제정신을 찾으셨어요! 거울 조각을 토해 내시고는 고맙다고 전하라 하셨어요.',
      '그런데 조각이 하나 더 있대요. 용궁 뒤 샘물길을 따라 올라가면 여름 골짜기가 나오는데, 거기 냇물이 독으로 물들고 있대요.',
      '남쪽 큰 대합이 길을 막고 있죠? 제가 열어 드릴게요. 골짜기 어귀에 포수 아저씨가 산대요.',
    ], gateAfter: 'valley', reward: { exp: 420 } },
  { title: '골짜기의 포수', type: 'talk', npc: 'hunter', desc: '용궁 남동쪽 샘물길 너머 <b>청류 계곡</b>의 <b>포수 만복</b>을 찾아가자',
    lines: () => [
      '어허, 바닷속에서 사람이 올라오다니! 난 이 골짜기에서 사냥하는 포수 만복이오.',
      '요즘 멧돼지가 미쳐 날뛰고, 사마귀 요괴가 낫을 휘두르고, 왕벌이 떼로 몰려다니오.',
      '냇물에 들어가면 발이 무거워지니 나무다리나 징검돌로 건너시오.',
    ] },
  { title: '골짜기 소동', type: 'kill', region: 'valley', need: { boar: 8, mantis: 6 }, desc: '골짜기의 <b>멧돼지</b>와 <b>사마귀 요괴</b>를 물리치자', reward: { exp: 820 } },
  { title: '왕벌 독침', type: 'collect', region: 'valley', item: '왕벌 독침', from: ['bee'], chance: 0.55, n: 6, desc: '<b>왕벌 요괴</b>를 쓰러뜨려 <b>왕벌 독침</b>을 모으자', reward: { exp: 760, item: 'cls:4' },
    startLines: ['만복: 냇물을 물들인 건 천년 묵은 왕지네요. 놈은 왕벌 독 냄새를 맡으면 기어 나오지.', '만복: 왕벌 독침을 여섯 개만 모아 오시오. 독 방울에 맞으면 몸이 무거워지니 조심하고!'] },
  { title: '솟대의 순서', type: 'order', region: 'valley', n: 4, prop: 'sotdae', added: 4, wrongLine: '순서가 틀렸다! 산짐승이 성을 낸다', desc: '<b>새가 적게 앉은 솟대부터</b> 차례로 두드리자 (솟대 앞에서 E)', reward: { exp: 740 },
    startLines: ['만복: 산신 제단에 촛불을 켜기 전에 솟대 넷을 깨워야 하오.', '만복: 새가 적게 앉은 솟대부터 많은 솟대 순서요. 틀리면 산짐승이 성을 낼 거요.'] },
  { title: '산신 제단', type: 'light', region: 'valley', n: 3, desc: '골짜기 곳곳의 <b>산신 제단</b>에 촛불을 밝히자 (제단 앞에서 E)', reward: { exp: 700 },
    startLines: ['만복: 산신님께 먼저 고해야 하오. 제단 셋에 촛불을 밝혀 주시오.'] },
  { title: '물레방아', type: 'wave', region: 'valley', desc: '냇가의 <b>물레방아</b>를 돌려 <b>천년 왕지네</b>와 맞서자', reward: { exp: 1500 },
    startLines: ['만복: 독침을 물레방아에 걸어 두었소. 바퀴를 돌리면 냄새가 퍼져 놈이 올 거요.', '만복: 몸을 낮추면 돌진하오. 독액 부채는 옆으로 피하시오!'] },
  { title: '고원 길', type: 'talk', npc: 'hunter', desc: '골짜기 어귀의 <b>포수 만복</b>에게 돌아가자',
    lines: () => [
      '왕지네를 잡다니! 냇물이 다시 맑아졌소. 이 골짜기 사람들 대신 고맙다 하리다.',
      '헌데 놈의 껍질 속에서 나온 거울 조각이 자꾸 남쪽 고원을 가리키오. 한여름인데 거기만 눈보라가 친다오.',
      '남서쪽 넝쿨 바위를 치워 두리다. 고원엔 심마니 영감이 혼자 버티고 계시오.',
    ], gateAfter: 'snowfield', reward: { exp: 450 } },
  { title: '설원의 심마니', type: 'talk', npc: 'ginseng', desc: '계곡 남서쪽 고원 길 너머 <b>백설 고원</b>의 <b>심마니 영감</b>을 찾아가자',
    lines: () => [
      '허허, 이 눈보라를 뚫고 왔소? 난 산삼 캐는 심마니요. 마을 사람들은 다 내려가고 나만 남았지.',
      '겨울 장수 동장군이 깨어나 이 고원을 얼려 버렸소. 눈늑대가 떼로 다니고, 얼음 도깨비에게 맞으면 몸이 얼어붙소.',
      '먼저 늑대와 도깨비들부터 쫓아 주시오.',
    ] },
  { title: '눈보라 속 사냥', type: 'kill', region: 'snowfield', need: { wolf: 10, icedok: 6 }, desc: '고원의 <b>눈늑대</b>와 <b>얼음 도깨비</b>를 물리치자', reward: { exp: 950 } },
  { title: '설삼', type: 'collect', region: 'snowfield', item: '설삼', from: ['icewisp', 'icedok'], chance: 0.45, n: 6, desc: '<b>서리 도깨비불</b>과 <b>얼음 도깨비</b>에게서 <b>설삼</b>을 모으자', reward: { exp: 880, item: 'ot11' },
    startLines: ['심마니: 동장군의 냉기를 견디려면 눈 속에서 자라는 설삼을 먹어야 하오.', '심마니: 얼음 요괴들이 설삼을 품고 다니니 여섯 뿌리만 모아 오시오.'] },
  { title: '화톳불', type: 'light', region: 'snowfield', n: 3, desc: '버려진 마을의 꺼진 <b>화톳불</b>을 피우자 (화톳불 앞에서 E)', reward: { exp: 820 },
    startLines: ['심마니: 화톳불 셋을 피우면 동장군이 불빛을 보고 성이 나서 내려올 거요.'] },
  { title: '심마니의 길', type: 'escort', region: 'snowfield', npc: 'ginseng', added: 4, ambushLine: '눈늑대가 덮친다! 심마니를 지키자', desc: '<b>심마니 영감</b>을 얼음 북까지 지켜 드리자 (곁에 붙어 있어야 걸어요)', reward: { exp: 860 },
    startLines: ['심마니: 얼음 북 아래 묻어 둔 백 년 산삼이 있소. 그걸 먹어야 동장군의 냉기를 견디지.', '심마니: 눈보라 속엔 혼자 못 가오. 곁에서 늑대를 막아 주시오!'] },
  { title: '얼음 북', type: 'wave', region: 'snowfield', desc: '고원 한가운데 <b>얼음 북</b>을 울려 <b>서리 거인 동장군</b>과 맞서자', reward: { exp: 1800 },
    startLines: ['심마니: 북을 울리면 동장군이 나오오. 뛰어오르면 떨어질 자리를, 하늘이 하얘지면 고드름을 피하시오!'] },
  { title: '귀환', type: 'talk', npc: 'guard', desc: '월하궁의 <b>수문장</b>에게 돌아가 소식을 전하자',
    lines: (g) => [
      `${g.player.cfg.title} 나리! 저승사자에 이무기, 불가사리, 백호, 용왕, 왕지네에 동장군까지 물리치셨다고요? 소문이 궁 안까지 퍼졌소!`,
      '이제 궁도, 대숲도, 옛 절터도, 늪과 협곡, 산성과 바다, 골짜기와 고원까지 모두 평안하오. 참으로 고맙소.',
      '그 거울 조각들… 깨진 달거울이로구려! 아홉 조각이 모였으니 남은 건 하나뿐이오.',
      '마지막 조각은 저승에 있다 하오. 협곡 대장간 옆에 열린 저승 문으로 시련탑에 올라, 열 번째 층의 염라대왕을 만나 보시오.',
      '현상수배가 붙으면 내게 오시오. 그동안 이 땅은 내가 지키고 있겠소.',
      '(메인 퀘스트 완료! 시련탑 10층의 염라대왕을 물리치면 엔딩을 볼 수 있습니다. 현상수배를 받거나, 북·방울·범종·징·풀무·봉화·용고·물레방아·얼음 북을 다시 울려 회차를 올릴 수도 있습니다)',
    ], reward: { exp: 400, item: 'cls:3' } },
];

// 메인 퀘스트 이후: 수문장이 주는 현상수배 (반복)
export const BOUNTIES = [
  { region: 'bamboo', title: '현상수배: 죽림 여우 떼', need: { fox: 8, foxfire: 3 } },
  { region: 'temple', title: '현상수배: 설원의 망자', need: { jiangshi: 6, ghost: 4 } },
  { region: 'bamboo', title: '현상수배: 여우불 소탕', need: { foxfire: 6 } },
  { region: 'temple', title: '현상수배: 강시 무리', need: { jiangshi: 10 } },
  { region: 'swamp', title: '현상수배: 늪의 물귀신', need: { waterghost: 8 } },
  { region: 'swamp', title: '현상수배: 독두꺼비', need: { toad: 6 } },
  { region: 'canyon', title: '현상수배: 화염 도깨비', need: { firedok: 8 } },
  { region: 'canyon', title: '현상수배: 걸어 다니는 장승', need: { stonegolem: 4 } },
  { region: 'fortress', title: '현상수배: 산적 도깨비', need: { bandit: 10 } },
  { region: 'fortress', title: '현상수배: 식인 범', need: { tiger: 5 } },
  { region: 'sea', title: '현상수배: 꽃게 떼', need: { crab: 10 } },
  { region: 'sea', title: '현상수배: 독해파리', need: { jelly: 8 } },
  { region: 'valley', title: '현상수배: 성난 멧돼지', need: { boar: 8 } },
  { region: 'valley', title: '현상수배: 왕벌 떼', need: { bee: 8 } },
  { region: 'snowfield', title: '현상수배: 눈늑대 무리', need: { wolf: 10 } },
  { region: 'snowfield', title: '현상수배: 얼음 도깨비', need: { icedok: 6 } },
];

export const KILL_NAME = { fox: '여우', foxfire: '여우불', jiangshi: '강시', ghost: '원귀', waterghost: '물귀신', toad: '두꺼비 요괴', firedok: '화염 도깨비', stonegolem: '돌장승', bandit: '산적 도깨비', crow: '까마귀 요괴', tiger: '범', crab: '꽃게 병사', jelly: '해파리', turtle: '거북 장군', boar: '멧돼지', mantis: '사마귀 요괴', bee: '왕벌 요괴', wolf: '눈늑대', icedok: '얼음 도깨비', icewisp: '서리 도깨비불', blue: '꼬마 도깨비', red: '붉은 도깨비', wisp: '도깨비불' };
