#!/usr/bin/env python3
"""캐릭터 스킨 시트 만들기 (LPC 레이어 합성) — js/skins.js의 SKINS와 짝

Usage:
  git clone --depth 1 https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator ulpc
  python3 tools/build_skins.py ulpc/spritesheets assets/sprites

무기는 무기 외형(js/looks.js)이 따로 그리므로 무기 없는 시트(<이름>_nw.png)만 만듭니다.
assets/sprites/skins_meta.js에 각 시트의 애니메이션 행 정보를 적습니다 (기본 직업 시트와 같은 LPC 배치).
"""
import json
import os
import sys

from build_sprites import load, W, H  # noqa: E402  (같은 폴더)
from PIL import Image

# 남자 기사 / 여자 요정 / 여자 마법사 — 기본 직업 시트와 같은 몸, 옷과 색만 다름
SKINS = {
    # ---- 기사 ----
    "skin_k_royal": [
        "shadow/adult/shadow.png",
        "cape/solid_behind/blue.png",
        "body/bodies/male/light.png",
        "legs/armour/plate/male/silver.png",
        "feet/armour/plate/male/silver.png",
        "torso/armour/plate/male/silver.png",
        "cape/solid/male/blue.png",
        "head/heads/human/male/light.png",
        "hair/plain/male/blonde.png",
    ],
    "skin_k_crimson": [
        "shadow/adult/shadow.png",
        "cape/solid_behind/red.png",
        "body/bodies/male/light.png",
        "legs/armour/plate/male/copper.png",
        "feet/armour/plate/male/copper.png",
        "torso/armour/plate/male/copper.png",
        "cape/solid/male/red.png",
        "head/heads/human/male/light.png",
        "hair/spiked/male/red.png",
    ],
    "skin_k_legion": [
        "shadow/adult/shadow.png",
        "cape/solid_behind/black.png",
        "body/bodies/male/bronze.png",
        "legs/armour/plate/male/brass.png",
        "feet/armour/plate/male/brass.png",
        "torso/armour/legion/male/brass.png",
        "cape/solid/male/black.png",
        "head/heads/human/male/bronze.png",
        "hair/plain/male/white.png",
    ],
    # ---- 요정 ----
    "skin_e_night": [
        "shadow/adult/shadow.png",
        "body/bodies/female/light.png",
        "legs/pants/female/black.png",
        "feet/boots/female/black.png",
        "torso/armour/leather/female/charcoal.png",
        "head/heads/human/female/light.png",
        "hair/long/female/raven.png",
    ],
    "skin_e_snow": [
        "shadow/adult/shadow.png",
        "body/bodies/female/light.png",
        "legs/pants/female/white.png",
        "feet/boots/female/white.png",
        "torso/armour/leather/female/sky.png",
        "head/heads/human/female/light.png",
        "hair/long/female/white.png",
    ],
    "skin_e_dawn": [
        "shadow/adult/shadow.png",
        "body/bodies/female/amber.png",
        "legs/pants/female/orange.png",
        "feet/boots/female/brown.png",
        "torso/armour/leather/female/yellow.png",
        "head/heads/human/female/amber.png",
        "hair/long/female/gold.png",
    ],
    # ---- 마법사 ----
    "skin_m_flame": [
        "shadow/adult/shadow.png",
        "cape/solid_behind/black.png",
        "body/bodies/female/light.png",
        "legs/skirts/plain/female/maroon.png",
        "feet/boots/female/black.png",
        "torso/clothes/blouse_longsleeve/female/red.png",
        "cape/solid/female/black.png",
        "head/heads/human/female/light.png",
        "hair/ponytail/female/red.png",
    ],
    "skin_m_abyss": [
        "shadow/adult/shadow.png",
        "cape/solid_behind/purple.png",
        "body/bodies/female/light.png",
        "legs/skirts/plain/female/black.png",
        "feet/boots/female/black.png",
        "torso/clothes/blouse_longsleeve/female/purple.png",
        "cape/solid/female/lavender.png",
        "head/heads/human/female/light.png",
        "hair/ponytail/female/violet.png",
    ],
    "skin_m_star": [
        "shadow/adult/shadow.png",
        "cape/solid_behind/white.png",
        "body/bodies/female/olive.png",
        "legs/skirts/plain/female/sky.png",
        "feet/boots/female/white.png",
        "torso/clothes/blouse_longsleeve/female/sky.png",
        "cape/solid/female/white.png",
        "head/heads/human/female/olive.png",
        "hair/ponytail/female/platinum.png",
    ],
}
BASE_ROWS = {"skin_k": "knight", "skin_e": "elf", "skin_m": "mage"}


def main():
    root, out = sys.argv[1], sys.argv[2]
    missing = []
    for name, layers in SKINS.items():
        sheet = Image.new("RGBA", (W, H))
        for rel in layers:
            img = load(root, rel)
            if img is None:
                missing.append(f"{name}: {rel}")
                continue
            sheet.alpha_composite(img)
        sheet.save(os.path.join(out, f"{name}_nw.png"), optimize=True)
        print("built", name)
    # 행 정보: 같은 몸을 쓰는 기본 직업 시트의 값을 그대로 씀 (meta.js가 먼저 로드됨)
    lines = ["// generated by tools/build_skins.py — 캐릭터 스킨 시트 (js/skins.js)",
             "(function () {", "  const R = window.SPRITE_ROWS;"]
    for name in SKINS:
        lines.append(f"  R['{name}_nw'] = R['{BASE_ROWS[name[:6]]}'];")
    lines.append("})();")
    with open(os.path.join(out, "skins_meta.js"), "w") as f:
        f.write("\n".join(lines) + "\n")
    if missing:
        print("MISSING LAYERS:\n  " + "\n  ".join(missing))
        sys.exit(1)


if __name__ == "__main__":
    main()
